
export const mainRoutes = {
    home: '/',
    auth: '/auth',
    login: '/auth/login',
    loginCliente: '/auth/login?user=clientes',
    loginEmpleados:'/auth/login?user=empleados',
    register: '/auth/register',
    recuperar_password: '/auth/recuperar_password',
    verificar_codigo_recuperacion: '/auth/verificar_codigo_recuperacion',
    mi_cuenta: '/mi_cuenta',
    prescripcion: '/prescripcion',
    auditoria: '/auditoria',
    gestion: '/gestion',
    form: '/formulario',
    etiqueta: '/etiqueta',
    plan_produccion: '/plan_produccion',
    reportePrescripcion: '/reporte',
    ayuda: '/ayuda',
    pdf: '/pdfprint',
    archivo_plano: '/archivo_plano',
}