
export const iconsNameMacrosectores: string[] = [
    'AGROPECUARIO Y AGROINDUSTRIAL',
    'COMERCIO',
    'CONSTRUCCION Y ENERGIA',
    'EDUCACION',
    'INDUSTRIA DE TURISMO',
    'INDUSTRIAS CREATIVAS, CULTURALES Y GRAFICAS',
    'INGENIERIA',
    'METALMECANICO Y AUTOMOTRIZ',
    'MODA',
    'SALUD Y QUIMICOS',
    'SERVICIOS EMPRESARIALES',
    'SOCIAL',
    'TIC',
];